#!/usr/bin/env bash
#Printing
trap "echo 'kill command'; rm /var/run/holbertonscript.pid; exit" SIGTERM
trap "echo" SIGINT
trap "rm /var/run/holbertonscript.pid; exit" SIGQUIT
echo $$ > /var/run/holbertonscript.pid
while true; do echo "To infinity and beyond"; sleep 2; done
