#!/usr/bin/env bash
#FizzBuzz in shell
for i in $(seq 1 100)
do
	if ((i % 3 == 0)) && ((i % 5 == 0))
	then
		echo "FizzBuzz"
	elif ((i % 3 == 0))
	then
		echo "Fizz"
	elif ((i % 5 == 0))
	then
		echo "Buzz"
	else
		echo "$i"
	fi
done
