#!/usr/bin/env bash
#Prints 10 times and different at 4 and 8
while((i++ < 10)); do if [ $i == 4 ]; then echo "bad luck"; elif [ $i == 8 ]; then echo "good luck"; else echo "Holberton School"; fi; done
