#!/usr/bin/env bash
#Change the host
cp /etc/hosts ~/tempy
echo "8.8.8.8	facebook.com" >> ~/tempy
sed -i "s/.*localhost/127.0.0.2	localhost/g" ~/tempy
sed -i "s/.*facebook.com/8.8.8.8    facebook.com/g" ~/tempy
cp -f ~/tempy /etc/host
